on:
  # Workflows check plugin Jeedom
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main
      
name : 'Full Workflows Plugin Jeedom'

jobs:
  plugin:
    uses: jeedom/workflows/.github/workflows/plugin.yml@main
